### ISSUE TITLE
Better example

### ISSUE THREAD

**Issue by Frikki** [axefrog/cycle-router5#1]
Could you please make a better example of how to use this router? Perhaps show a setup like [an example](http://router5.github.io/docs/with-deku.html#/inbox) found on the official router5 page.

I think you are assuming cycle users to "be in the know", which isn’t particularly the case.

Many thanks!

**Comment by axefrog** [comment]
Sure, I'll try to find some time in the next few days.

**Comment by Frikki** [comment]
:+1:

**Comment by basham** [comment]
:+1:

**Comment by axefrog** [comment]
I've updated the driver and added a better example to the readme file. Let me know if you have any issues with the driver.

**Comment by basham** [comment]
@Frikki I worked on an example yesterday, which includes hot module loading. Very rough. But its enough for me to get a better feel for these tools.
https://github.com/basham/cycle-demo/tree/router5

And here's another version, using [`cycle-director`](https://github.com/tylors/cycle-director).
https://github.com/basham/cycle-demo/tree/director

**Comment by basham** [comment]
@axefrog Thanks for the work on your example.
