### ISSUE TITLE
Use default export

### ISSUE THREAD

**Issue by ivan-kleshnin** [axefrog/cycle-router5#2]
Minor issue but just as easy to fix.

Currently, your lib exports single function:

``` js
export function makeRouterDriver(routes, options) {...}
```

Which allows two types of imports:

``` js
import * as CycleRouter5 from "cycle-router5";
// or
import {makeRouterDriver} from "cycle-router5";
```

It would be better if the export style was:

``` js
function makeRouterDriver(routes, options) {...}

export default {
  makeRouterDriver
};
```

Which would allow better namespaced import:

``` js
import CycleRouter5 from "cycle-router5";

// compare to ugly
// import * as CycleRouter5 from "cycle-router5";

// keeps the same
import {makeRouterDriver} from "cycle-router5";
```

There is a rule of thumb that every library should always declare a default export to make client code easier. In ES6 we can even combine "default" and "shared" exports in the same module.

**Comment by axefrog** [comment]
@ivan-kleshnin done, thanks I wasn't overly savvy on the nuances of ES6 module syntax.
